<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="\view\style.css">
    <title>Document</title>
</head>
<body>
    <div class="main">
        <header>
            <span>список абитуриентов</span> 
            <div>
                <span>поиск:</span>
                <input type="search" name="q">
                <input type="submit" id="submitB" value="[найти]"></input>
            </div>
        </header>
        <div class="tableOut">
            <table width="100%">
                <tr>
                    <td>Имя</td>
                    <td>Фамилия</td>
                    <td>Номер группы</td>
                    <td>Баллов</td>
                </tr>
            </table>
            <table width="100% " class="line">
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </table>
        </div>
        <span>
            Страницы:
        </span>
    </div>
    <?= var_dump($rows); ?>
</body>
</html>