<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="\view\style.css">
    <title>Document</title>
</head>
<body>
<div class="main">
    <header>
        <span>список абитуриентов</span>
        <div>
            <span>поиск:</span>
            <input type="search" name="q">
            <input type="submit" id="submitB" value="[найти]"></input>
        </div>
    </header>
    <div class="tableOut">
        <table width="100%">
            <tr>
                <td>Имя</td>
                <td>Фамилия</td>
                <td>Номер группы</td>
                <td>Баллы</td>
            </tr>
        </table>
        <table width="100% " class="line">
            <?php foreach($students as $partList):
                foreach($partList as $row):?>
                <tr>
                    <td><?= $row['firstName'] ?></php></td>
                    <td><?= $row['lastName'] ?></td>
                    <td><?= $row['groupName'] ?></td>
                    <td><?= $row['score'] ?></td>
                </tr>
            <?php endforeach;
            endforeach;?>
        </table>
    </div>
    <span>
            Страницы:
    </span>
</div>
</body>
</html>